### ISSUE TITLE
CMake error: Unable to find the requested Boost libraries

### ISSUE THREAD

**Issue by neha-ojha** [noahdesu/zlog#135]
I am trying to run cmake . and see the following error. I have Ceph installed with the cls_zlog plugin loaded.

CMake Warning at /usr/share/cmake/Modules/FindBoost.cmake:743 (message):
  Imported targets not available for Boost version
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindBoost.cmake:842 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake/Modules/FindBoost.cmake:1395 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:31 (find_package)

CMake Warning at /usr/share/cmake/Modules/FindBoost.cmake:743 (message):
  Imported targets not available for Boost version
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindBoost.cmake:842 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake/Modules/FindBoost.cmake:1395 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:31 (find_package)

CMake Error at /usr/share/cmake/Modules/FindBoost.cmake:1753 (message):
  Unable to find the requested Boost libraries.

  Unable to find the Boost header files.  Please set BOOST_ROOT to the root
  directory containing Boost or BOOST_INCLUDEDIR to the directory containing
  Boost's headers.
Call Stack (most recent call first):
  CMakeLists.txt:31 (find_package)

-- Building Ceph backend /usr/local/lib64/librados.so
-- Configuring incomplete, errors occurred!

**Comment by noahdesu** [comment]
what is the output of `rpm -qa | grep boost`

**Comment by neha-ojha** [comment]
This is the output of dnf list installed|grep boost.

boost.x86_64                             1.60.0-10.fc25                @updates 
boost-atomic.x86_64                      1.60.0-10.fc25                @updates 
boost-atomic.x86_64                      1.63.0-6.fc27                 @System  
boost-chrono.x86_64                      1.60.0-10.fc25                @updates 
boost-container.x86_64                   1.60.0-10.fc25                @updates 
boost-context.x86_64                     1.60.0-10.fc25                @updates 
boost-coroutine.x86_64                   1.60.0-10.fc25                @updates 
boost-date-time.x86_64                   1.60.0-10.fc25                @updates 
boost-devel.x86_64                       1.60.0-10.fc25                @updates 
boost-filesystem.x86_64                  1.60.0-10.fc25                @updates 
boost-graph.x86_64                       1.60.0-10.fc25                @updates 
boost-iostreams.x86_64                   1.60.0-10.fc25                @updates 
boost-locale.x86_64                      1.60.0-10.fc25                @updates 
boost-log.x86_64                         1.60.0-10.fc25                @updates 
boost-math.x86_64                        1.60.0-10.fc25                @updates 
boost-program-options.x86_64             1.60.0-10.fc25                @updates 
boost-python.x86_64                      1.60.0-10.fc25                @updates 
boost-random.x86_64                      1.60.0-10.fc25                @updates 
boost-regex.x86_64                       1.60.0-10.fc25                @updates 
boost-serialization.x86_64               1.60.0-10.fc25                @updates 
boost-signals.x86_64                     1.60.0-10.fc25                @updates 
boost-system.x86_64                      1.60.0-10.fc25                @updates 
boost-test.x86_64                        1.60.0-10.fc25                @updates 
boost-thread.x86_64                      1.60.0-10.fc25                @updates 
boost-timer.x86_64                       1.60.0-10.fc25                @updates 
boost-type_erasure.x86_64                1.60.0-10.fc25                @updates 
boost-wave.x86_64                        1.60.0-10.fc25                @updates 
ibus-typing-booster.noarch               1.5.30-1.fc25                 @updates

**Comment by neha-ojha** [comment]
Output of ./install-deps.sh

Last metadata expiration check: 1:27:52 ago on Tue Apr 18 13:47:07 2017.
Dependencies resolved.
Nothing to do.
Complete!
Last metadata expiration check: 1:27:54 ago on Tue Apr 18 13:47:07 2017.
Dependencies resolved.
Nothing to do.
Complete!
Last metadata expiration check: 1:27:55 ago on Tue Apr 18 13:47:07 2017.
Package boost-devel-1.60.0-10.fc25.x86_64 is already installed, skipping.
Package cmake-3.6.2-6.fc25.x86_64 is already installed, skipping.
Package gcc-c++-6.3.1-1.fc25.x86_64 is already installed, skipping.
Package java-1.8.0-openjdk-devel-1:1.8.0.121-10.b14.fc25.x86_64 is already installed, skipping.
Package lcov-1.12-1.fc25.noarch is already installed, skipping.
Package libatomic-6.3.1-1.fc25.x86_64 is already installed, skipping.
Package lmdb-devel-0.9.19-1.fc25.x86_64 is already installed, skipping.
Package protobuf-compiler-2.6.1-5.fc25.x86_64 is already installed, skipping.
Package protobuf-devel-2.6.1-5.fc25.x86_64 is already installed, skipping.
Dependencies resolved.
Nothing to do.
Complete!
Last metadata expiration check: 1:27:56 ago on Tue Apr 18 13:47:07 2017.
Dependencies resolved.
Nothing to do.
Complete!

**Comment by neha-ojha** [comment]
sudo dnf install boost-devel

Last metadata expiration check: 1:32:39 ago on Tue Apr 18 13:47:07 2017.
Package boost-devel-1.60.0-10.fc25.x86_64 is already installed, skipping.
Dependencies resolved.
Nothing to do.
Complete!

**Comment by neha-ojha** [comment]
sudo dnf install boost-devel
Last metadata expiration check: 1:49:15 ago on Tue Apr 18 13:47:07 2017.
Error: package boost-devel-1.60.0-10.fc25.x86_64 requires libboost_atomic.so.1.60.0()(64bit), but none of the providers can be installed
(try to add '--allowerasing' to command line to replace conflicting packages)
[nojha@localhost zlog]$ sudo dnf install boost-devel
Last metadata expiration check: 1:50:00 ago on Tue Apr 18 13:47:07 2017.
Error: package boost-devel-1.60.0-9.fc25.x86_64 requires libboost_atomic.so.1.60.0()(64bit), but none of the providers can be installed
(try to add '--allowerasing' to command line to replace conflicting packages)

**Comment by noahdesu** [comment]
Looks like a non-zlog issue based on offline discussion.
