### ISSUE TITLE
test: re-enable C api tests

### ISSUE THREAD

**Issue by noahdesu** [noahdesu/zlog#86]
This depends on the C api support backends in #85 
##

**Comment by RabsRincon** [comment]
For the record, that's https://github.com/noahdesu/zlog/blob/master/src/include/zlog/capi.h and https://github.com/noahdesu/zlog/blob/master/src/libzlog/capi.cc

**Comment by noahdesu** [comment]
fixed. c api tests now run with lmdb and ceph backends.
